export const projects = [
  {
    name: "Which pizza",
    text: "which-pizza is an app to compare pizza sizes and prices. If wondering which pizza combinations in better price value, you can just fill in the form with diameter, amount and prices of pizza. App is counting total area of both options and price per square area as well as choosing which is more worthy. User can also choose they measure unit (centimeters or inches) and local currency. App is using free API to get all actual currencies. This simple one-pager application is fully responsive.",
    subtext: null,
    points: null,
    demo: "https://which-pizza-app.netlify.app/",
    github: "https://github.com/brzeczkowskaw/which-pizza",
    tools: [
      "Vue3",
      "TypeScript",
      "HTML",
      "CSS",
      "Vuetify",
      "Pinia",
      "Axios",
      "Vite",
      "lottie",
      "pluralize",
    ],
    photos: ["WhichPizza", "WhichPizzaResults"],
  },
  {
    name: "Cocktail wizard",
    text: "cocktail-wizard app allows you to find cocktail recepies. On main page, you receive random cocktails. You can search cockatils for several categories: name, ingredient, alcohol content, category, glass. After choosing the cocktail, you will receive details about it: picture, ingredients, tags and preparation.",
    subtext: "You can login to get additional features:",
    points: [
      "save cocktails to your favourite list",
      "create your bar: you can save ingredients you can have in your bar. You can search for cocktails made with your ingredients",
      "when looking for a cocktail details, we check the ingredients on the list, which you have in your bar.",
    ],
    demo: "https://cocktail-wizard-app.netlify.app/",
    github: "https://github.com/brzeczkowskaw/cocktail-wizard/",
    tools: [
      "Vue",
      "TypeScript",
      "HTML",
      "CSS",
      "Vuetify",
      "Pinia",
      "Axios",
      "Vite",
      "Vue Router",
      "lottie",
      "firebase",
      "firestore",
    ],
    photos: [
      "CocktailWizard",
      "CocktailWizardBar",
      "CocktailWizardFavourites",
      "CocktailWizardRecipie",
      "CocktailWizardLogin",
    ],
  },
];