export const projects = [
  {
    name: "Which-Pizza",
    text: "Which-Pizza is an user-friendly app for comparing pizza sizes and prices. Input the diameter, quantity, and prices to find the best value. The app calculates total area and price per square unit to help you decide. Customize units and currency, with up-to-date rates from a free API. Fully responsive for easy use on any device.",
    subtext: null,
    points: null,
    demo: "https://which-pizza-app.netlify.app/",
    github: "https://github.com/brzeczkowskaw/which-pizza",
    tools: [
      "Vue3",
      "TypeScript",
      "HTML",
      "CSS",
      "Vuetify",
      "Pinia",
      "Axios",
      "Vite",
      "lottie",
      "pluralize",
      "open API"
    ],
    photos: ["WhichPizza", "WhichPizzaResults"],
  },
  {
    name: "Cocktail Wizard",
    text: "Cocktail Wizard is your go-to app for discovering cocktail recipes. Upon landing on the main page, you're greeted with a selection of random cocktails. Dive deeper by searching for cocktails based on various categories such as name, ingredient, alcohol content, category, or glass type. Once you've selected a cocktail, you'll receive comprehensive details including a picture, ingredients, tags, and preparation instructions. Cheers to your next perfect drink!",
    subtext: "You can login to get additional features:",
    points: [
      "save cocktails to your favourite list",
      "create your bar: you can save ingredients you can have in your bar. You can search for cocktails made with your ingredients",
      "when looking for a cocktail details, we check the ingredients on the list, which you have in your bar.",
    ],
    demo: "https://cocktail-wizard-app.netlify.app/",
    github: "https://github.com/brzeczkowskaw/cocktail-wizard/",
    tools: [
      "Vue",
      "TypeScript",
      "HTML",
      "CSS",
      "Vuetify",
      "Pinia",
      "Axios",
      "Vite",
      "Vue Router",
      "lottie",
      "firebase",
      "firestore",
      "open API",
    ],
    photos: [
      "CocktailWizard",
      "CocktailWizardBar",
      "CocktailWizardFavourites",
      "CocktailWizardRecipie",
      "CocktailWizardLogin",
    ],
  },
];